import type { LucideIcon } from "lucide-react";
import {
  Activity,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ClipboardList,
  Clock,
  DatabaseZap,
  GitCompareArrows,
  Map as MapIcon,
  PieChart,
  Scale,
  Target,
  TrendingDown,
  UserCircle2,
  UserCog,
  BriefcaseBusiness,
  UserSquare,
} from "lucide-react";

export type ModuleStatus = "active" | "hidden" | "internal";
export type ModuleNavigationGroup = "Dashboard" | "Gestion" | "Administracion" | "Personal";
export type ModuleAccessSection = "Dashboard / Indicadores" | "Gestion" | "Administracion" | "Personal" | "Paneles";

export type CatalogModule = {
  key: string;
  label: string;
  title: string;
  eyebrow: string;
  summary: string;
  href: string;
  icon: LucideIcon;
  navigationGroup: ModuleNavigationGroup;
  trail: string[];
  accessSection: ModuleAccessSection;
  status: ModuleStatus;
  mobileVisible?: boolean;
};

export const STARTER_NAME = "CoreX";
export const STARTER_SUBTITLE = "Centro de Inteligencia Empresarial";

export const MODULE_CATALOG: CatalogModule[] = [
  {
    key: "campo-mapa",
    label: "Mapa",
    title: "Mapa",
    eyebrow: "Dashboard / Indicadores / Campo",
    summary: "Historial espacial de bloques con apertura por bloque padre.",
    href: "/dashboard/campo",
    icon: MapIcon,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Campo"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
  },
  {
    key: "campo-fenograma",
    label: "Fenograma",
    title: "Fenograma",
    eyebrow: "Dashboard / Indicadores / Campo",
    summary: "Pivot semanal de corte y desvío por ciclo.",
    href: "/dashboard/fenograma",
    icon: CalendarRange,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Campo"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
  },
  {
    key: "campo-mortality",
    label: "Mortandades",
    title: "Mortandades",
    eyebrow: "Dashboard / Indicadores / Campo",
    summary: "Mortandad por ciclo con curva ponderada y apertura al historial del bloque.",
    href: "/dashboard/mortality",
    icon: Activity,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Campo"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
  },
  {
    key: "campo-comparacion",
    label: "Comparación",
    title: "Comparación",
    eyebrow: "Dashboard / Indicadores / Campo",
    summary: "Cruce uno a uno entre ciclos activos.",
    href: "/dashboard/comparacion",
    icon: GitCompareArrows,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Campo"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
  },
  {
    key: "campo-productividad",
    label: "Productividad",
    title: "Productividad",
    eyebrow: "Dashboard / Indicadores / Campo",
    summary: "Productividad de mano de obra: horas por caja por ciclo y etapa operativa.",
    href: "/dashboard/productividad",
    icon: Clock,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Campo"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
  },
  {
    key: "postcosecha-balanzas",
    label: "Balanzas",
    title: "Indicadores Balanzas",
    eyebrow: "Dashboard / Indicadores / Postcosecha",
    summary: "Apertura B1 vs B1C sobre el flujo de postcosecha para peso y tallos.",
    href: "/dashboard/postcosecha/balanzas",
    icon: Scale,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Postcosecha"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
  },
  {
    key: "talento-composicion",
    label: "Composición laboral",
    title: "Composición laboral",
    eyebrow: "Dashboard / Indicadores / Talento Humano",
    summary: "Distribución del personal activo por área, cargo, empresa y clasificación.",
    href: "/dashboard/talento-humano/composicion-laboral",
    icon: PieChart,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Talento Humano"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-demografia",
    label: "Demografía personal",
    title: "Demografía personal",
    eyebrow: "Dashboard / Indicadores / Talento Humano",
    summary: "Distribución demográfica del personal activo por género, estado civil, ciudad y contrato.",
    href: "/dashboard/talento-humano/demografia-personal",
    icon: UserCircle2,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Talento Humano"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-rotacion",
    label: "Rotación laboral",
    title: "Rotación laboral",
    eyebrow: "Dashboard / Indicadores / Talento Humano",
    summary: "Ingresos, salidas y tasa de rotación por semana.",
    href: "/dashboard/talento-humano/rotacion-laboral",
    icon: TrendingDown,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Talento Humano"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-seguimientos",
    label: "Seguimientos",
    title: "Seguimientos Trabajo Social",
    eyebrow: "Gestión / Talento Humano / Registros",
    summary: "Registro de seguimientos de Trabajo Social: consulta programados y registra respuestas AGR/ADM.",
    href: "/dashboard/talento-humano/seguimientos",
    icon: UserSquare,
    navigationGroup: "Gestion",
    trail: ["Talento Humano", "Registros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-dominios",
    label: "Dominios",
    title: "Dominios TTHH",
    eyebrow: "Gestión / Talento Humano / Administrar Maestros",
    summary: "Dominios que agrupan catálogos por formulario o proceso de Talento Humano.",
    href: "/dashboard/talento-humano/administrar-maestros/dominios",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Talento Humano", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-catalogos",
    label: "Catálogos",
    title: "Catálogos TTHH",
    eyebrow: "Gestión / Talento Humano / Administrar Maestros",
    summary: "Administración de catálogos y opciones para formularios de Talento Humano.",
    href: "/dashboard/talento-humano/administrar-maestros/catalogos",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Talento Humano", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "calidad-punto-apertura",
    label: "Punto de apertura",
    title: "Punto de apertura",
    eyebrow: "Dashboard / Indicadores / Calidad",
    summary: "Indicadores de calidad para seguimiento de punto de apertura.",
    href: "/dashboard/calidad/punto-apertura",
    icon: Activity,
    navigationGroup: "Dashboard",
    trail: ["Indicadores", "Calidad"],
    accessSection: "Dashboard / Indicadores",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "gestion-programaciones",
    label: "Programaciones",
    title: "Programaciones",
    eyebrow: "Gestión / Campo / Planificación",
    summary: "Calendario de programaciones de campo: plantas muertas, iluminación, fumigación, drench, GA3 y riego.",
    href: "/dashboard/programaciones",
    icon: CalendarClock,
    navigationGroup: "Gestion",
    trail: ["Campo", "Planificación"],
    accessSection: "Gestion",
    status: "active",
  },
  {
    key: "campo-drench-program",
    label: "Programacion Drench",
    title: "Programacion Drench",
    eyebrow: "Gestion / Campo / Administrar Maestros",
    summary: "Reglas editables de drench por semana fenologica, tipo de ciclo y variedad, vinculadas a productos FM11 de Bodega.",
    href: "/dashboard/campo/administrar-maestros/programacion-drench",
    icon: ClipboardList,
    navigationGroup: "Gestion",
    trail: ["Campo", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-productos",
    label: "Productos",
    title: "Productos",
    eyebrow: "GestiÃ³n / Bodega / Administrar Maestros",
    summary: "Maestro corporativo de productos e insumos administrado por Bodega.",
    href: "/dashboard/bodega/administrar-maestros/productos",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Bodega", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-unidades",
    label: "Unidades",
    title: "Unidades",
    eyebrow: "GestiÃ³n / Bodega / Administrar Maestros",
    summary: "Maestro operativo de unidades base para productos y conversiones de Bodega.",
    href: "/dashboard/bodega/administrar-maestros/unidades",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Bodega", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-categorias",
    label: "Configurar catalogo",
    title: "Configurar catalogo",
    eyebrow: "GestiÃ³n / Bodega / Administrar Maestros",
    summary: "Arbol maestro de tipo, familia y subfamilia para clasificar productos de Bodega.",
    href: "/dashboard/bodega/administrar-maestros/categorias",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Bodega", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-presentaciones",
    label: "Presentaciones y conversiones",
    title: "Presentaciones y conversiones",
    eyebrow: "GestiÃ³n / Bodega / Administrar Maestros",
    summary: "Presentaciones comerciales y conversiones a la unidad base dominante del producto.",
    href: "/dashboard/bodega/administrar-maestros/presentaciones-conversiones",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Bodega", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "personal-mi-cuenta",
    label: "Mi cuenta",
    title: "Mi cuenta",
    eyebrow: "Personal",
    summary: "Perfil local, preferencias visuales, ruta por defecto y notificaciones personales.",
    href: "/dashboard/mi-cuenta",
    icon: UserCircle2,
    navigationGroup: "Personal",
    trail: [],
    accessSection: "Personal",
    status: "active",
  },
  {
    key: "personal-mi-trabajo",
    label: "Workspace",
    title: "Workspace",
    eyebrow: "Personal",
    summary: "Tareas, eventos, calendario, agenda y recordatorios del usuario autenticado.",
    href: "/dashboard/mi-trabajo",
    icon: BriefcaseBusiness,
    navigationGroup: "Personal",
    trail: [],
    accessSection: "Personal",
    status: "active",
  },
  {
    key: "postcosecha-registros",
    label: "Registros",
    title: "Registros",
    eyebrow: "Gestión / Postcosecha / Registros",
    summary: "Ruta reservada para registros operativos de postcosecha.",
    href: "/dashboard/postcosecha/registros",
    icon: ClipboardList,
    navigationGroup: "Gestion",
    trail: ["Postcosecha"],
    accessSection: "Gestion",
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "postcosecha-skus",
    label: "Administrar SKU's",
    title: "Administrar SKU's",
    eyebrow: "Gestión / Postcosecha / Administrar Maestros",
    summary: "Maestro transaccional de SKU para alimentar el solver de clasificación en blanco.",
    href: "/dashboard/postcosecha/administrar-maestros/skus",
    icon: DatabaseZap,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Administrar Maestros"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "postcosecha-programaciones",
    label: "Programaciones",
    title: "Programaciones",
    eyebrow: "Gestión / Postcosecha / Planificación",
    summary: "Ruta reservada para la programación operativa de postcosecha.",
    href: "/dashboard/postcosecha/planificacion/programaciones",
    icon: CalendarClock,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Planificación"],
    accessSection: "Gestion",
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "postcosecha-plan-trabajo",
    label: "Plan de trabajo",
    title: "Plan de trabajo",
    eyebrow: "Gestión / Postcosecha / Planificación",
    summary: "Ruta reservada para consolidar el plan de trabajo de postcosecha.",
    href: "/dashboard/postcosecha/planificacion/plan-de-trabajo",
    icon: CalendarDays,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Planificación"],
    accessSection: "Gestion",
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "postcosecha-clasificacion",
    label: "Clasificación en blanco",
    title: "Clasificación en blanco",
    eyebrow: "Gestión / Postcosecha / Planificación / Solver",
    summary: "Solver operativo para clasificación en blanco con datos del maestro SKU.",
    href: "/dashboard/postcosecha/planificacion/solver/clasificacion-en-blanco",
    icon: Scale,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Planificación", "Solver"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-usuarios",
    label: "Usuarios",
    title: "Usuarios",
    eyebrow: "Administración / Seguridad",
    summary: "Gestión de usuarios, roles y permisos por recurso.",
    href: "/dashboard/admin/seguridad/usuarios",
    icon: UserCog,
    navigationGroup: "Administracion",
    trail: ["Seguridad"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-metrics",
    label: "Métricas",
    title: "Métricas",
    eyebrow: "Administración / Administración Maestros / Métricas",
    summary: "Maestro de métricas reutilizables para objetivos, metas y tableros.",
    href: "/dashboard/admin/administracion-maestros/metricas",
    icon: Target,
    navigationGroup: "Administracion",
    trail: ["Administración Maestros"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-goals",
    label: "Metas & Objetivos",
    title: "Metas & Objetivos",
    eyebrow: "Administración / Administración Maestros / Metas & Objetivos",
    summary: "Administración de métricas, objetivos, metas y dimensiones del sistema.",
    href: "/dashboard/admin/administracion-maestros/metas-objetivos",
    icon: Target,
    navigationGroup: "Administracion",
    trail: ["Administración Maestros"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-masters-overview",
    label: "Administración Maestros",
    title: "Administración Maestros",
    eyebrow: "Administración / Administración Maestros",
    summary: "Gestión centralizada de catálogos, maestros y estructuras administrativas del sistema.",
    href: "/dashboard/admin/administracion-maestros",
    icon: Target,
    navigationGroup: "Administracion",
    trail: [],
    accessSection: "Administracion",
    status: "hidden",
    mobileVisible: false,
  },
];

export const ALL_MANAGED_MODULES = MODULE_CATALOG.filter((catalogEntry) => catalogEntry.status !== "internal");
export const ACTIVE_MODULES = MODULE_CATALOG.filter((catalogEntry) => catalogEntry.status === "active");
export const ACTIVE_MODULE_MAP = new globalThis.Map(ACTIVE_MODULES.map((catalogEntry) => [catalogEntry.href, catalogEntry]));
export const MANAGED_MODULE_MAP = new globalThis.Map(ALL_MANAGED_MODULES.map((catalogEntry) => [catalogEntry.href, catalogEntry]));
export const ACTIVE_RESOURCE_KEYS = new Set(ACTIVE_MODULES.map((catalogEntry) => catalogEntry.href));
export const ALL_MANAGED_RESOURCE_KEYS = new Set(ALL_MANAGED_MODULES.map((catalogEntry) => catalogEntry.href));

export function filterModulesByAccess<T extends { href: string }>(
  modules: T[],
  allowedResources: string[],
  isSuperadmin: boolean,
) {
  return modules.filter((catalogEntry) => isSuperadmin || allowedResources.includes(catalogEntry.href));
}

export function findModuleByPath(pathname: string) {
  return MODULE_CATALOG.find(
    (catalogEntry) => pathname === catalogEntry.href || pathname.startsWith(`${catalogEntry.href}/`),
  ) ?? null;
}
