import type { LucideIcon } from "lucide-react";
import {
  Activity,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ClipboardCheck,
  ClipboardList,
  Clock,
  DatabaseZap,
  GitCompareArrows,
  Map as MapIcon,
  PieChart,
  Scale,
  Target,
  TrendingDown,
  UserCircle2,
  UserCog,
  UsersRound,
  BriefcaseBusiness,
  UserSquare,
  UserX,
  Beaker,
} from "lucide-react";

export type ModuleStatus = "active" | "hidden" | "internal";
export type ModuleNavigationGroup = "Dashboard" | "Gestion" | "Administracion" | "Personal";
export type ModuleAccessSection = "Analítica / Indicadores & KPI" | "Gestion" | "Administracion" | "Personal" | "Paneles";

export type CatalogModule = {
  key: string;
  label: string;
  title: string;
  eyebrow: string;
  summary: string;
  href: string;
  icon: LucideIcon;
  navigationGroup: ModuleNavigationGroup;
  trail: string[];
  accessSection: ModuleAccessSection;
  status: ModuleStatus;
  mobileVisible?: boolean;
  quickAccess?: boolean;
  keywords?: string[];
};

export const STARTER_NAME = "CoreX";
export const STARTER_SUBTITLE = "Centro de Inteligencia Empresarial";

export const MODULE_CATALOG: CatalogModule[] = [
  {
    key: "campo-mapa",
    label: "Mapa",
    title: "Mapa",
    eyebrow: "Analítica / Campo / Indicadores & KPI",
    summary: "Historial espacial de bloques con apertura por bloque padre.",
    href: "/dashboard/campo",
    icon: MapIcon,
    navigationGroup: "Dashboard",
    trail: ["Campo", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
  },
  {
    key: "campo-fenograma",
    label: "Fenograma",
    title: "Fenograma",
    eyebrow: "Analítica / Campo / Indicadores & KPI",
    summary: "Pivot semanal de corte y desvío por ciclo.",
    href: "/dashboard/fenograma",
    icon: CalendarRange,
    navigationGroup: "Dashboard",
    trail: ["Campo", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    quickAccess: true,
  },
  {
    key: "campo-mortality",
    label: "Mortalidad",
    title: "Mortalidad",
    eyebrow: "Analítica / Campo / Indicadores & KPI",
    summary: "Mortandad por ciclo con curva ponderada y apertura al historial del bloque.",
    href: "/dashboard/mortality",
    icon: Activity,
    navigationGroup: "Dashboard",
    trail: ["Campo", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    quickAccess: true,
  },
  {
    key: "campo-comparacion",
    label: "Comparación",
    title: "Comparación",
    eyebrow: "Analítica / Campo / Indicadores & KPI",
    summary: "Cruce uno a uno entre ciclos activos.",
    href: "/dashboard/comparacion",
    icon: GitCompareArrows,
    navigationGroup: "Dashboard",
    trail: ["Campo", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
  },
  {
    key: "campo-productividad",
    label: "Productividad",
    title: "Productividad",
    eyebrow: "Analítica / Campo / Indicadores & KPI",
    summary: "Productividad de mano de obra: horas por caja por ciclo y etapa operativa.",
    href: "/dashboard/productividad",
    icon: Clock,
    navigationGroup: "Dashboard",
    trail: ["Campo", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    quickAccess: true,
  },
  {
    key: "postcosecha-balanzas",
    label: "Balanzas",
    title: "Balanzas",
    eyebrow: "Analítica / Postcosecha / Indicadores & KPI",
    summary: "Apertura B1 vs B1C sobre el flujo de postcosecha para peso y tallos.",
    href: "/dashboard/postcosecha/balanzas",
    icon: Scale,
    navigationGroup: "Dashboard",
    trail: ["Postcosecha", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    quickAccess: true,
  },
  {
    key: "talento-composicion",
    label: "Composición laboral",
    title: "Composición laboral",
    eyebrow: "Analítica / Talento Humano / Indicadores & KPI",
    summary: "Distribución del personal activo por área, cargo, empresa y clasificación.",
    href: "/dashboard/talento-humano/composicion-laboral",
    icon: PieChart,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-demografia",
    label: "Demografía del personal",
    title: "Demografía del personal",
    eyebrow: "Analítica / Talento Humano / Indicadores & KPI",
    summary: "Distribución demográfica del personal activo por género, estado civil, ciudad y contrato.",
    href: "/dashboard/talento-humano/demografia-personal",
    icon: UserCircle2,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-rotacion",
    label: "Rotación laboral",
    title: "Rotación laboral",
    eyebrow: "Analítica / Talento Humano / Indicadores & KPI",
    summary: "Ingresos, salidas y tasa de rotación por semana.",
    href: "/dashboard/talento-humano/rotacion-laboral",
    icon: TrendingDown,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-desvinculacion",
    label: "Desvinculación personal",
    title: "Desvinculación personal",
    eyebrow: "Analítica / Talento Humano / Indicadores & KPI",
    summary: "Motivos de salida, antigüedad del evento y rendimiento previo a la desvinculación.",
    href: "/dashboard/talento-humano/desvinculacion-personal",
    icon: UserX,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-colaboradores",
    label: "Colaboradores",
    title: "Colaboradores",
    eyebrow: "Analítica / Talento Humano / Explorador",
    summary: "Explorador integral por colaborador con permisos granulares por seccion y filtros.",
    href: "/dashboard/talento-humano/colaboradores",
    icon: UsersRound,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Explorador"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-simulador-vacaciones",
    label: "Simulador de Vacaciones",
    title: "Simulador de Vacaciones",
    eyebrow: "Analítica / Talento Humano / Explorador",
    summary: "Provisión y disponibilidad de vacaciones por colaborador activo según fecha de corte.",
    href: "/dashboard/talento-humano/simulador-vacaciones",
    icon: CalendarDays,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Explorador"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-herramienta-desvinculacion",
    label: "Herramienta de Desvinculación",
    title: "Herramienta de Desvinculación",
    eyebrow: "Analítica / Talento Humano / Explorador",
    summary: "Rendimiento semanal agregado por colaborador activo, base para señales de desvinculación.",
    href: "/dashboard/talento-humano/herramienta-desvinculacion",
    icon: Activity,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Explorador"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-indicador-seguimientos",
    label: "Seguimientos",
    title: "Seguimientos",
    eyebrow: "Analítica / Talento Humano / Indicadores & KPI",
    summary: "Cumplimiento de seguimientos de Trabajo Social por trabajadora, área y período.",
    href: "/dashboard/talento-humano/indicador-seguimientos",
    icon: ClipboardCheck,
    navigationGroup: "Dashboard",
    trail: ["Talento Humano", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-seguimientos",
    label: "Seguimientos",
    title: "Seguimientos Trabajo Social",
    eyebrow: "Gestión / Talento Humano / Registros",
    summary: "Registro de seguimientos de Trabajo Social: consulta programados y registra respuestas AGR/ADM.",
    href: "/dashboard/talento-humano/seguimientos",
    icon: UserSquare,
    navigationGroup: "Gestion",
    trail: ["Talento Humano", "Registros"],
    accessSection: "Gestion",
    status: "active",
    quickAccess: true,
    mobileVisible: false,
  },
  {
    key: "talento-dominios",
    label: "Dominios",
    title: "Dominios TTHH",
    eyebrow: "Administración / Maestros por dominio / Talento Humano / Dominios",
    summary: "Dominios que agrupan catálogos por formulario o proceso de Talento Humano.",
    href: "/dashboard/talento-humano/administrar-maestros/dominios",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Talento Humano"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "talento-catalogos",
    label: "Catálogos",
    title: "Catálogos TTHH",
    eyebrow: "Administración / Maestros por dominio / Talento Humano / Catálogos",
    summary: "Administración de catálogos y opciones para formularios de Talento Humano.",
    href: "/dashboard/talento-humano/administrar-maestros/catalogos",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Talento Humano"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "calidad-punto-apertura",
    label: "Punto de apertura",
    title: "Punto de apertura",
    eyebrow: "Analítica / Calidad / Indicadores & KPI",
    summary: "Indicadores de calidad para seguimiento de punto de apertura.",
    href: "/dashboard/calidad/punto-apertura",
    icon: Activity,
    navigationGroup: "Dashboard",
    trail: ["Calidad", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "calidad-reclamos",
    label: "Reclamos",
    title: "Reclamos",
    eyebrow: "Analítica / Calidad / Reclamos",
    summary: "Visualizador estadístico de alertas, notas de crédito, motivos y estados del proceso de reclamos.",
    href: "/dashboard/calidad/reclamos",
    icon: Activity,
    navigationGroup: "Dashboard",
    trail: ["Calidad", "Indicadores & KPI"],
    accessSection: "Analítica / Indicadores & KPI",
    // hidden por defecto: tras la integración del frente reclamos el usuario
    // asigna acceso manualmente desde Admin · Seguridad · Usuarios y luego
    // cambia status a "active" cuando esté listo para que aparezca en el
    // sidebar. Mantenerlo "hidden" evita auto-grant a usuarios viewer.
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "comercial-reclamos",
    label: "Reclamos",
    title: "Reclamos",
    eyebrow: "Gestión / Comercial / Reclamos",
    summary: "Módulo transaccional de reclamos para registro, aprobaciones y aplicaciones.",
    href: "/dashboard/comercial/reclamos",
    icon: ClipboardList,
    navigationGroup: "Gestion",
    trail: ["Comercial", "Reclamos"],
    accessSection: "Gestion",
    // hidden por defecto: ver nota en calidad-reclamos. El usuario activa
    // el módulo y asigna permisos cuando esté listo para producción.
    status: "hidden",
    quickAccess: true,
    mobileVisible: false,
  },
  {
    key: "gestion-programaciones",
    label: "Programaciones",
    title: "Programaciones",
    eyebrow: "Gestión / Campo / Planificación",
    summary: "Calendario de programaciones de campo: plantas muertas, iluminación, fumigación, drench, GA3 y riego.",
    href: "/dashboard/programaciones",
    icon: CalendarClock,
    navigationGroup: "Gestion",
    trail: ["Campo", "Planificación"],
    accessSection: "Gestion",
    status: "active",
    quickAccess: true,
  },
  {
    key: "campo-drench-program",
    label: "Programación Drench",
    title: "Programación Drench",
    eyebrow: "Administración / Maestros por dominio / Campo / Programación Drench",
    summary: "Reglas editables de drench por semana fenologica, tipo de ciclo y variedad, vinculadas a productos FM11 de Bodega.",
    href: "/dashboard/campo/administrar-maestros/programacion-drench",
    icon: ClipboardList,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Campo"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "laboratorio-product-recipes",
    label: "Recetas de productos",
    title: "Recetas de productos",
    eyebrow: "Administración / Maestros por dominio / Laboratorio / Recetas de productos",
    summary: "Productos nacidos en Laboratorio con receta interna basada en insumos de Bodega y vinculacion por activity_id.",
    href: "/dashboard/laboratorio/administrar-maestros/receta-productos",
    icon: Beaker,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Laboratorio"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "laboratorio-product-types",
    label: "Tipos de elaboración",
    title: "Tipos de elaboración",
    eyebrow: "Administración / Maestros por dominio / Laboratorio / Tipos de elaboración",
    summary: "Maestro simple de tipos para clasificar productos de Laboratorio, por ejemplo Hongos.",
    href: "/dashboard/laboratorio/administrar-maestros/tipos-elaboracion",
    icon: Beaker,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Laboratorio"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "comercial-clientes",
    label: "Clientes",
    title: "Clientes",
    eyebrow: "Administración / Maestros por dominio / Comercial / Clientes",
    summary: "Maestro comercial de clientes usado por notas y alertas de reclamo.",
    href: "/dashboard/comercial/administrar-maestros/clientes",
    icon: BriefcaseBusiness,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Comercial"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "comercial-comercializadoras",
    label: "Comercializadoras",
    title: "Comercializadoras",
    eyebrow: "Administración / Maestros por dominio / Comercial / Comercializadoras",
    summary: "Maestro de comercializadoras para el flujo operativo de reclamos.",
    href: "/dashboard/comercial/administrar-maestros/comercializadoras",
    icon: BriefcaseBusiness,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Comercial"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "comercial-ejecutivos-cuenta",
    label: "Ejecutivos de cuenta",
    title: "Ejecutivos de cuenta",
    eyebrow: "Administración / Maestros por dominio / Comercial / Ejecutivos de cuenta",
    summary: "Maestro de ejecutivos de cuenta vinculado a Talento Humano, con fallback manual solo para cod_personal NA.",
    href: "/dashboard/comercial/administrar-maestros/ejecutivos-cuenta",
    icon: BriefcaseBusiness,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Comercial"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "general-variedades",
    label: "Variedades",
    title: "Variedades",
    eyebrow: "Administración / Maestros por dominio / General / Variedades",
    summary: "Catalogo general inicial de variedades para reclamos y otros procesos transversales.",
    href: "/dashboard/general/administrar-maestros/variedades",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "General"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "postcosecha-destinos",
    label: "Destinos",
    title: "Destinos",
    eyebrow: "Administración / Maestros por dominio / Postcosecha / Destinos",
    summary: "Catálogo de destinos de postcosecha que en reclamos se mostrará visualmente como Proceso.",
    href: "/dashboard/postcosecha/administrar-maestros/destinos",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Postcosecha"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "general-fincas",
    label: "Fincas",
    title: "Fincas",
    eyebrow: "Administración / Maestros por dominio / General / Fincas",
    summary: "Maestro general inicial de fincas para reclamos y otros procesos transversales.",
    href: "/dashboard/general/administrar-maestros/fincas",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "General"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "comercial-problemas-reclamo",
    label: "Problemas de reclamo",
    title: "Problemas de reclamo",
    eyebrow: "Administracion / Maestros por dominio / Comercial / Problemas de reclamo",
    summary: "Arbol maestro de tipos de problema y problemas operativos para notas y alertas de reclamo.",
    href: "/dashboard/comercial/administrar-maestros/problemas-reclamo",
    icon: BriefcaseBusiness,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Comercial"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-programaciones",
    label: "Programaciones",
    title: "Programaciones",
    eyebrow: "Gestión / Bodega / Planificación",
    summary: "Calendarizacion semanal de drench por semana ISO para preparar la programacion que luego consume Bodega.",
    href: "/dashboard/bodega/planificacion/programaciones",
    icon: CalendarClock,
    navigationGroup: "Gestion",
    trail: ["Bodega", "Planificación"],
    accessSection: "Gestion",
    status: "active",
    quickAccess: true,
    mobileVisible: false,
  },
  {
    key: "bodega-productos",
    label: "Productos",
    title: "Productos",
    eyebrow: "Administración / Maestros por dominio / Bodega / Productos",
    summary: "Maestro corporativo de productos e insumos administrado por Bodega.",
    href: "/dashboard/bodega/administrar-maestros/productos",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Bodega"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-unidades",
    label: "Unidades",
    title: "Unidades",
    eyebrow: "Administración / Maestros por dominio / Bodega / Unidades",
    summary: "Maestro operativo de unidades base para productos y conversiones de Bodega.",
    href: "/dashboard/bodega/administrar-maestros/unidades",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Bodega"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-categorias",
    label: "Catálogos",
    title: "Catálogos",
    eyebrow: "Administración / Maestros por dominio / Bodega / Catálogos",
    summary: "Arbol maestro de familia y subfamilia para clasificar productos de Bodega.",
    href: "/dashboard/bodega/administrar-maestros/categorias",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Bodega"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "bodega-presentaciones",
    label: "Presentaciones y conversiones",
    title: "Presentaciones y conversiones",
    eyebrow: "Administración / Maestros por dominio / Bodega / Presentaciones y conversiones",
    summary: "Presentaciones comerciales y conversiones a la unidad base dominante del producto.",
    href: "/dashboard/bodega/administrar-maestros/presentaciones-conversiones",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Bodega"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "personal-mi-cuenta",
    label: "Mi cuenta",
    title: "Mi cuenta",
    eyebrow: "Personal",
    summary: "Perfil local, preferencias visuales, ruta por defecto y notificaciones personales.",
    href: "/dashboard/mi-cuenta",
    icon: UserCircle2,
    navigationGroup: "Personal",
    trail: [],
    accessSection: "Personal",
    status: "active",
  },
  {
    key: "personal-mi-trabajo",
    label: "Workspace",
    title: "Workspace",
    eyebrow: "Personal",
    summary: "Tareas, eventos, calendario, agenda y recordatorios del usuario autenticado.",
    href: "/dashboard/mi-trabajo",
    icon: BriefcaseBusiness,
    navigationGroup: "Personal",
    trail: [],
    accessSection: "Personal",
    status: "active",
  },
  {
    key: "postcosecha-registros",
    label: "Registros",
    title: "Registros",
    eyebrow: "Gestión / Postcosecha / Registros",
    summary: "Ruta reservada para registros operativos de postcosecha.",
    href: "/dashboard/postcosecha/registros",
    icon: ClipboardList,
    navigationGroup: "Gestion",
    trail: ["Postcosecha"],
    accessSection: "Gestion",
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "postcosecha-skus",
    label: "SKU's",
    title: "SKU's",
    eyebrow: "Administración / Maestros por dominio / Postcosecha / SKU's",
    summary: "Maestro transaccional de SKU para alimentar el solver de clasificación en blanco.",
    href: "/dashboard/postcosecha/administrar-maestros/skus",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros por dominio", "Postcosecha"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "postcosecha-programaciones",
    label: "Programaciones",
    title: "Programaciones",
    eyebrow: "Gestión / Postcosecha / Planificación",
    summary: "Ruta reservada para la programación operativa de postcosecha.",
    href: "/dashboard/postcosecha/planificacion/programaciones",
    icon: CalendarClock,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Planificación"],
    accessSection: "Gestion",
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "postcosecha-plan-trabajo",
    label: "Plan de trabajo",
    title: "Plan de trabajo",
    eyebrow: "Gestión / Postcosecha / Planificación",
    summary: "Ruta reservada para consolidar el plan de trabajo de postcosecha.",
    href: "/dashboard/postcosecha/planificacion/plan-de-trabajo",
    icon: CalendarDays,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Planificación"],
    accessSection: "Gestion",
    status: "hidden",
    mobileVisible: false,
  },
  {
    key: "postcosecha-clasificacion",
    label: "Clasificación en blanco",
    title: "Clasificación en blanco",
    eyebrow: "Gestión / Postcosecha / Planificación / Solver",
    summary: "Solver operativo para clasificación en blanco con datos del maestro SKU.",
    href: "/dashboard/postcosecha/planificacion/solver/clasificacion-en-blanco",
    icon: Scale,
    navigationGroup: "Gestion",
    trail: ["Postcosecha", "Planificación", "Solver"],
    accessSection: "Gestion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-usuarios",
    label: "Usuarios",
    title: "Usuarios",
    eyebrow: "Administración / Seguridad",
    summary: "Gestión de usuarios, roles y permisos por recurso.",
    href: "/dashboard/admin/seguridad/usuarios",
    icon: UserCog,
    navigationGroup: "Administracion",
    trail: ["Seguridad"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-dominios",
    label: "Dominios",
    title: "Dominios",
    eyebrow: "Administración / Maestros globales / Dominios",
    summary: "Macro-dominios usados en metas, objetivos y agrupación de catálogos.",
    href: "/dashboard/admin/administracion-maestros/dominios",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros globales"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-catalogos",
    label: "Catálogos",
    title: "Catálogos",
    eyebrow: "Administración / Maestros globales / Catálogos",
    summary: "Listas de opciones reutilizables (tipos de meta, operadores, direcciones, etc.).",
    href: "/dashboard/admin/administracion-maestros/catalogos",
    icon: DatabaseZap,
    navigationGroup: "Administracion",
    trail: ["Maestros globales"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-unidades",
    label: "Unidades",
    title: "Unidades de medida",
    eyebrow: "Administración / Maestros globales / Unidades",
    summary: "Maestro de unidades de medida (kg, %, horas, tallos, etc.) para métricas y tableros.",
    href: "/dashboard/admin/administracion-maestros/unidades",
    icon: Scale,
    navigationGroup: "Administracion",
    trail: ["Maestros globales"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-metrics",
    label: "Métricas",
    title: "Métricas",
    eyebrow: "Administración / Maestros globales / Métricas",
    summary: "Maestro de métricas reutilizables para objetivos, metas y tableros.",
    href: "/dashboard/admin/administracion-maestros/metricas",
    icon: Target,
    navigationGroup: "Administracion",
    trail: ["Maestros globales"],
    accessSection: "Administracion",
    status: "active",
    quickAccess: true,
    mobileVisible: false,
  },
  {
    key: "admin-goals",
    label: "Metas y objetivos",
    title: "Metas y objetivos",
    eyebrow: "Administración / Maestros globales / Metas y objetivos",
    summary: "Administración de métricas, objetivos, metas y dimensiones del sistema.",
    href: "/dashboard/admin/administracion-maestros/metas-objetivos",
    icon: Target,
    navigationGroup: "Administracion",
    trail: ["Maestros globales"],
    accessSection: "Administracion",
    status: "active",
    mobileVisible: false,
  },
  {
    key: "admin-masters-overview",
    label: "Maestros globales",
    title: "Maestros globales",
    eyebrow: "Administración / Maestros globales",
    summary: "Gestión centralizada de catálogos, maestros y estructuras administrativas del sistema.",
    href: "/dashboard/admin/administracion-maestros",
    icon: Target,
    navigationGroup: "Administracion",
    trail: [],
    accessSection: "Administracion",
    status: "hidden",
    mobileVisible: false,
  },
];

export const ALL_MANAGED_MODULES = MODULE_CATALOG.filter((catalogEntry) => catalogEntry.status !== "internal");
export const ACTIVE_MODULES = MODULE_CATALOG.filter((catalogEntry) => catalogEntry.status === "active");
export const ACTIVE_MODULE_MAP = new globalThis.Map(ACTIVE_MODULES.map((catalogEntry) => [catalogEntry.href, catalogEntry]));
export const MANAGED_MODULE_MAP = new globalThis.Map(ALL_MANAGED_MODULES.map((catalogEntry) => [catalogEntry.href, catalogEntry]));
export const ACTIVE_RESOURCE_KEYS = new Set(ACTIVE_MODULES.map((catalogEntry) => catalogEntry.href));
export const ALL_MANAGED_RESOURCE_KEYS = new Set(ALL_MANAGED_MODULES.map((catalogEntry) => catalogEntry.href));

export function filterModulesByAccess<T extends { href: string }>(
  modules: T[],
  allowedResources: string[],
  isSuperadmin: boolean,
) {
  return modules.filter((catalogEntry) => isSuperadmin || allowedResources.includes(catalogEntry.href));
}

export function findModuleByPath(pathname: string) {
  return MODULE_CATALOG.find(
    (catalogEntry) => pathname === catalogEntry.href || pathname.startsWith(`${catalogEntry.href}/`),
  ) ?? null;
}

